/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary ラーメン一覧を取得
 */
export const orvalGetRamensQueryLimitDefault = 10;
export const orvalGetRamensQueryLimitMax = 100;
export const orvalGetRamensQueryOffsetDefault = 0;
export const orvalGetRamensQueryOffsetMin = 0;


export const orvalGetRamensQueryParams = zod.object({
  "limit": zod.number().min(1).max(orvalGetRamensQueryLimitMax).default(orvalGetRamensQueryLimitDefault).describe('取得件数の上限'),
  "offset": zod.number().min(orvalGetRamensQueryOffsetMin).optional().describe('取得開始位置'),
  "orders": zod.string().optional().describe('ソート順'),
  "q": zod.string().optional().describe('検索クエリ'),
  "fields": zod.string().optional().describe('取得するフィールドを指定'),
  "ids": zod.string().optional().describe('特定のIDのコンテンツのみ取得'),
  "filters": zod.string().optional().describe('フィルター条件')
})

export const orvalGetRamensResponseContentsItemRatingMax = 5;


export const orvalGetRamensResponse = zod.object({
  "contents": zod.array(zod.object({
  "id": zod.string().describe('ラーメンID'),
  "createdAt": zod.string().datetime({}).describe('作成日時'),
  "updatedAt": zod.string().datetime({}).describe('更新日時'),
  "publishedAt": zod.string().datetime({}).describe('公開日時'),
  "revisedAt": zod.string().datetime({}).describe('改訂日時'),
  "title": zod.string().describe('タイトル'),
  "description": zod.string().nullish().describe('説明'),
  "images": zod.array(zod.object({
  "url": zod.string().describe('画像URL'),
  "height": zod.number().describe('画像の高さ'),
  "width": zod.number().describe('画像の幅')
})).nullish().describe('画像リスト'),
  "visitDate": zod.string().datetime({}).nullish().describe('来店日'),
  "tags": zod.array(zod.enum(['ラーメン', '油そば', 'つけ麺', '家系', 'パスタ', '二郎系', '担々麺', '味噌', '醤油', '塩', '豚骨'])).nullish().describe('タグ'),
  "googleMapUrl": zod.string().nullish().describe('GoogleMapのURL'),
  "tabelogUrl": zod.string().nullish().describe('食べログのURL'),
  "rating": zod.number().min(1).max(orvalGetRamensResponseContentsItemRatingMax).nullish().describe('評価（1-5）'),
  "price": zod.number().nullish().describe('価格')
})),
  "totalCount": zod.number().describe('総件数'),
  "offset": zod.number().describe('取得開始位置'),
  "limit": zod.number().describe('取得件数の上限')
})

/**
 * @summary 特定のラーメン情報を取得
 */
export const orvalGetRamenByIdParams = zod.object({
  "id": zod.string().describe('ラーメンID')
})

export const orvalGetRamenByIdQueryParams = zod.object({
  "fields": zod.string().optional().describe('取得するフィールドを指定')
})

export const orvalGetRamenByIdResponseRatingMax = 5;


export const orvalGetRamenByIdResponse = zod.object({
  "id": zod.string().describe('ラーメンID'),
  "createdAt": zod.string().datetime({}).describe('作成日時'),
  "updatedAt": zod.string().datetime({}).describe('更新日時'),
  "publishedAt": zod.string().datetime({}).describe('公開日時'),
  "revisedAt": zod.string().datetime({}).describe('改訂日時'),
  "title": zod.string().describe('タイトル'),
  "description": zod.string().nullish().describe('説明'),
  "images": zod.array(zod.object({
  "url": zod.string().describe('画像URL'),
  "height": zod.number().describe('画像の高さ'),
  "width": zod.number().describe('画像の幅')
})).nullish().describe('画像リスト'),
  "visitDate": zod.string().datetime({}).nullish().describe('来店日'),
  "tags": zod.array(zod.enum(['ラーメン', '油そば', 'つけ麺', '家系', 'パスタ', '二郎系', '担々麺', '味噌', '醤油', '塩', '豚骨'])).nullish().describe('タグ'),
  "googleMapUrl": zod.string().nullish().describe('GoogleMapのURL'),
  "tabelogUrl": zod.string().nullish().describe('食べログのURL'),
  "rating": zod.number().min(1).max(orvalGetRamenByIdResponseRatingMax).nullish().describe('評価（1-5）'),
  "price": zod.number().nullish().describe('価格')
})

