/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */

export interface MediaItem {
  /** 画像URL */
  url: string;
  /** 画像の高さ */
  height: number;
  /** 画像の幅 */
  width: number;
}
