/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */

export type OrvalGetRamenTagsParams = {
/**
 * 取得件数の上限
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * 取得開始位置
 * @minimum 0
 */
offset?: number;
/**
 * ソート順
 */
orders?: string;
/**
 * 検索クエリ
 */
q?: string;
/**
 * 取得するフィールドを指定
 */
fields?: string;
/**
 * フィルター条件
 */
filters?: string;
};
