/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */

export type OrvalGetRamenByIdParams = {
/**
 * 取得するフィールドを指定
 */
fields?: string;
};
