/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Ramen } from './ramen';

export interface RamenListResponse {
  contents: Ramen[];
  /** 総件数 */
  totalCount: number;
  /** 取得開始位置 */
  offset: number;
  /** 取得件数の上限 */
  limit: number;
}
