/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * タグカテゴリ
 */
export type RamenTagCategory = typeof RamenTagCategory[keyof typeof RamenTagCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RamenTagCategory = {
  type: 'type',
  area: 'area',
  feature: 'feature',
  taste: 'taste',
  price: 'price',
  atmosphere: 'atmosphere',
  service: 'service',
} as const;
