/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */
import type { RamenTagCategoryItem } from './ramenTagCategoryItem';

export interface RamenTag {
  /** タグID */
  id: string;
  /** 作成日時 */
  createdAt: string;
  /** 更新日時 */
  updatedAt: string;
  /** 公開日時 */
  publishedAt: string;
  /** 改訂日時 */
  revisedAt: string;
  /** タグ名 */
  name: string;
  /** タグカテゴリ（配列形式） */
  category: RamenTagCategoryItem[];
  /**
   * タグの説明
   * @nullable
   */
  description?: string | null;
}
