/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */

export type RamenTagsItem = typeof RamenTagsItem[keyof typeof RamenTagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RamenTagsItem = {
  ラーメン: 'ラーメン',
  油そば: '油そば',
  つけ麺: 'つけ麺',
  家系: '家系',
  パスタ: 'パスタ',
  二郎系: '二郎系',
  担々麺: '担々麺',
  味噌: '味噌',
  醤油: '醤油',
  塩: '塩',
  豚骨: '豚骨',
} as const;
