/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */

export type RamenTagCategoryItem = typeof RamenTagCategoryItem[keyof typeof RamenTagCategoryItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RamenTagCategoryItem = {
  type: 'type',
  area: 'area',
  feature: 'feature',
  taste: 'taste',
  price: 'price',
  atmosphere: 'atmosphere',
  service: 'service',
} as const;
