/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */
import type { MediaItem } from './mediaItem';
import type { RamenTag } from './ramenTag';

export interface Ramen {
  /** ラーメンID */
  id: string;
  /** 作成日時 */
  createdAt: string;
  /** 更新日時 */
  updatedAt: string;
  /** 公開日時 */
  publishedAt: string;
  /** 改訂日時 */
  revisedAt: string;
  /** タイトル */
  title: string;
  /**
   * 説明
   * @nullable
   */
  description?: string | null;
  /**
   * 画像リスト
   * @nullable
   */
  images?: MediaItem[] | null;
  /**
   * 来店日
   * @nullable
   */
  visitDate?: string | null;
  /**
   * ラーメンタグ
   * @nullable
   */
  tags?: RamenTag[] | null;
  /**
   * GoogleMapのURL
   * @nullable
   */
  googleMapUrl?: string | null;
  /**
   * 食べログのURL
   * @nullable
   */
  tabelogUrl?: string | null;
  /**
   * 評価（1-5）
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  rating?: number | null;
  /**
   * 価格
   * @nullable
   */
  price?: number | null;
}
