/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * t4ichi blog API
 * t4ichi-blogのAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  OrvalGetRamenTagsParams,
  RamenTagListResponse
} from '../../schemas';

import { customFetch } from '../../customFetch';

/**
 * @summary ラーメンタグ一覧を取得
 */
export const getOrvalGetRamenTagsUrl = (params?: OrvalGetRamenTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/ramen-tags?${stringifiedParams}` : `/ramen-tags`
}

export const orvalGetRamenTags = async (params?: OrvalGetRamenTagsParams, options?: RequestInit): Promise<RamenTagListResponse> => {
  
  return customFetch<RamenTagListResponse>(getOrvalGetRamenTagsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


